### ISSUE TITLE
Commit email and author amend needed

### ISSUE THREAD

**Issue by Deck451** [jschaf/pylint-flask#19]
Please update email and author fields for commit 
[https://github.com/jschaf/pylint-flask/commit/920d716303bd9ea28c456f6bf785e95f2c256142](https://github.com/jschaf/pylint-flask/commit/920d716303bd9ea28c456f6bf785e95f2c256142)

**Comment by jschaf** [comment]
And done

**Comment by octavian451** [comment]
Thank you!
