### ISSUE TITLE
tests/input in release tarball

### ISSUE THREAD

**Issue by danstender** [jschaf/pylint-flask#2]
Hi Joe,

we're are packaging pylint-flask for Debian, and would like to run the tests automatically while building from the/a tarball. Could you please either tag the release(s) on Github or include test/input into the Pypi tarball (we could point to either)? Thx in advance, the package is coming up, soon!

Best,
DS

**Comment by jschaf** [comment]
Exciting!  I made it into Debian.

I did both.
I tagged v0.3 and added the test directory to the manifest, so it's included on pypi.

Lemme know if it works.

**Comment by danstender** [comment]
On 24.01.2016 00:36, Joe Schafer wrote:
> Exciting!  I made it into Debian.
> 
> I did both.
> I tagged v0.3 and added the test directory to the manifest, so it's included on pypi.
> 
> Lemme know if it works.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jschaf/pylint-flask/issues/2#issuecomment-174234313

Great, much thanks. I think we're going to pull the Github tarball then.

I've seen that there are some packages missing in Debian to run the tests right now
(flask-bcrypt, flask-admin), but the package is coming up anyway.

I'll drop a note when it's available.
 
Best,
DS

-- 
4096R/DF5182C8
46CB 1CA8 9EA3 B743 7676 1DB9 15E0 9AF4 DF51 82C8
LPI certified Linux admin (LPI000329859 64mz6f7kt4)
http://www.danielstender.com/blog/
